version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: ['area: ci', 'dependencies']

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: ['area: contract', 'dependencies']

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels: ['area: ci', 'dependencies']
